name: Deploy to Ubuntu Server

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Starting deployment..."

            # پاک کردن کامل دایرکتوری قبلی
            cd /var/www/crowd/
            rm -rf users
            mkdir -p users
            cd users

            echo "Cloning fresh repository..."
            git clone --depth 1 https://github.com/isatispooya/crowd-client.git . || { echo "Git clone failed"; exit 1; }

            echo "Installing dependencies..."
            rm -rf node_modules yarn.lock
            yarn install || { echo "yarn install failed"; exit 1; }

            echo "Installing Rollup..."
            yarn add rollup || { echo "Rollup install failed"; exit 1; }

            echo "Building project..."
            yarn build || { echo "Build failed"; exit 1; }

            if [ ! -d "dist" ] || [ ! -f "dist/index.html" ]; then
              echo "Error: dist folder or index.html not found"
              exit 1
            fi

            echo "Checking dist directory contents:"
            ls -la dist/

            echo "Restarting PM2 service..."
            pm2 delete crowdusers || echo "No existing PM2 process found"
            NODE_NO_WARNINGS=1 pm2 start serve --name crowdusers -- /var/www/crowd/users/dist -p 8110 -s || { echo "PM2 start failed"; exit 1; }
            pm2 save || { echo "PM2 save failed"; exit 1; }

            echo "Deployment completed successfully"
